# Generated by Django 4.2.18 on 2025-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapp", "0003_remove_medicalrecord_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="date_recorded",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
